# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email:
    on_success: change
    on_failure: always 
  recipients:
    - esobel@ucla.edu
    
install:
  - julia -e 'ENV["PYTHON"]=""; Pkg.build("PyCall")'
  - julia -e 'Pkg.clone("https://github.com/OpenMendel/SnpArrays.jl.git")'
  - julia -e 'Pkg.clone("https://github.com/OpenMendel/Search.jl.git")'
  - julia -e 'Pkg.clone("https://github.com/OpenMendel/MendelBase.jl.git")'
  
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("MendelGWAS"); Pkg.test("MendelGWAS"; coverage=true)'
